package com.saasplatform.audit.entity;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    TOKEN_REFRESH,
    PASSWORD_CHANGED,
    REGISTER_SUCCESS,

    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_UPGRADED,
    SUBSCRIPTION_CANCELLED,
    SUBSCRIPTION_RESUMED,

    PAYMENT_ORDER_CREATED,
    PAYMENT_VERIFIED,
    PAYMENT_FAILED,
    PAYMENT_WEBHOOK_PROCESSED,

    INVOICE_CREATED,

    USAGE_RECORDED,
    QUOTA_EXCEEDED,

    ADMIN_USER_STATUS_CHANGED,
    ADMIN_PLAN_UPDATED
}
